
name: Deploy Containers BillingApp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: This action has the scope to checkout repository code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Advise deployment has started
        run: echo Initialization complete, starting...

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker images
        run: | 
            ls
            ls ..
            echo Starting build...
            docker compose -f compose.yml build

      - name: Push Docker images
        run: docker compose -f compose.yml push

      - name: completion
        run: echo action has completed
